services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8003:8003"
    volumes:
      - ./gs_data:/app/gs_data
      - ./domains.json:/app/domains.json
      - ./backend/src:/app/backend/src
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "8004:8004"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: always

  database:
    image: mariadb:latest
    container_name: mariadb_service
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: parser_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    restart: always
